version: '3'

services:
  db:
    image: postgres:12
    container_name: postgres-adventureworks
    environment:
      POSTGRES_DB: adventureworks
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adventureworkspass
    volumes:
      - ./dbdata:/var/lib/postgresql/data
      - ./data:/data
      - ./install.sql:/docker-entrypoint-initdb.d/install.sql
    ports:
      - 5432:5432